#!/bin/sh

set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version=v1.6.0
output="$root/licenses/tailmix.md"
freetype_version=v0.0.0-20170609003504-e2365dfdc4a0

case ${1:-check} in
	check|update) mode=${1:-check} ;;
	*)
		echo "usage: $0 [check|update]" >&2
		exit 2
		;;
esac

tmp=$(mktemp -d "${TMPDIR:-/tmp}/tailmix-licenses.XXXXXX")
trap 'rm -rf "$tmp"' EXIT HUP INT TERM
mkdir "$tmp/bin"

GOBIN="$tmp/bin" go install "github.com/google/go-licenses@$version"
go_licenses="$tmp/bin/go-licenses"

actual_freetype_version=$(go list -m -f '{{.Version}}' github.com/golang/freetype)
if [ "$actual_freetype_version" != "$freetype_version" ]; then
	echo "github.com/golang/freetype changed from the reviewed $freetype_version to $actual_freetype_version" >&2
	echo "review its license and update the explicit exception in scripts/licenses.sh" >&2
	exit 1
fi

# packages lists the binaries shipped for a GOOS.
packages() {
	case $1 in
		windows) echo ./cmd/tailmix ./cmd/tailmixd ./cmd/tailmix-tray ;;
		*) echo ./cmd/tailmix ./cmd/tailmixd ;;
	esac
}

check_target() {
	goos=$1
	goarch=$2
	cgo_enabled=$3
	log="$tmp/check-$goos-$goarch.log"
	# shellcheck disable=SC2046 # word splitting of the package list is intended
	if env GOOS="$goos" GOARCH="$goarch" CGO_ENABLED="$cgo_enabled" "$go_licenses" check \
		$(packages "$goos") \
		--ignore github.com/maisem/tailmix \
		--ignore github.com/golang/freetype 2>"$log"; then
		return
	fi
	cat "$log" >&2
	return 1
}

report_target() {
	goos=$1
	goarch=$2
	cgo_enabled=$3
	destination=$4
	log="$tmp/report-$goos-$goarch.log"
	# shellcheck disable=SC2046 # word splitting of the package list is intended
	if env GOOS="$goos" GOARCH="$goarch" CGO_ENABLED="$cgo_enabled" "$go_licenses" report \
		$(packages "$goos") \
		--ignore github.com/maisem/tailmix \
		--template "$root/licenses/report.tmpl" >"$destination" 2>"$log"; then
		return
	fi
	cat "$log" >&2
	return 1
}

cd "$root"
check_target darwin arm64 1
check_target linux amd64 1
check_target windows amd64 0
report_target darwin arm64 1 "$tmp/darwin.md"
report_target linux amd64 1 "$tmp/linux.md"
report_target windows amd64 0 "$tmp/windows.md"

generated="$tmp/tailmix.md"
{
	printf '%s\n\n' '# tailmix binary dependencies'
	printf '%s\n' 'This file is generated by `make licenses` using'
	printf '%s\n' "[go-licenses $version](https://github.com/google/go-licenses/tree/$version)."
	printf '%s\n\n' 'Do not edit it by hand.'
	printf '%s\n' 'The report covers the supported tailmix, tailmixd and tailmix-tray build targets. The same'
	printf '%s\n\n' 'package can appear more than once when it contains multiple license files.'
	printf '%s\n\n' '## Darwin (arm64)'
	cat "$tmp/darwin.md"
	printf '\n%s\n\n' '## Linux (amd64)'
	cat "$tmp/linux.md"
	printf '\n%s\n\n' '## Windows (amd64)'
	cat "$tmp/windows.md"
} >"$generated"

if [ "$mode" = update ]; then
	install -m 0644 "$generated" "$output"
	exit 0
fi

if ! cmp -s "$generated" "$output"; then
	echo "licenses/tailmix.md is stale; run 'make licenses'" >&2
	diff -u "$output" "$generated" || true
	exit 1
fi
